[package]
name = "val_metaend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.1"
actix-cors = "0.6.4"
actix-web = "4.4.0"
amqp_serde = "0.4.0"
amqprs = "1.5.0"
futures = "0.3.29"
mongodb = "2.7.0"
serde = "1.0.189"
serde_bson = "0.0.1"
tokio = "1.33.0"
uuid = "1.5.0"
